# GitLab CI/CD Pipeline for deploying Vue 3 + Vite app to GitLab Pages
image: docker.io/library/node:lts

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

pages:
  stage: deploy
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
